modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="ansur"
version="1.0.0"
displayName="Ansur"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="tarku, MCreator"

[[dependencies.ansur]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




